version: '3.8'

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: todo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todo_network

  # Go приложение
  app:
    build: .
    container_name: todo_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=todo_user
      - DB_PASSWORD=todo_password
      - DB_NAME=todo_db
      - HOST=0.0.0.0
      - PORT=8080
    volumes:
      - .:/app
      - /app/tmp
      - /app/vendor
    depends_on:
      - postgres
    networks:
      - todo_network

volumes:
  postgres_data:

networks:
  todo_network:
    driver: bridge
